In [1]:
import numpy as np
import matplotlib.pyplot as plt

raw_data_x = [[3.39, 2.33],
              [3.11, 1.78],
              [1.34, 3.37],
              [3.58, 4.67],
              [2.28, 2.86],
              [7.42, 4.69],
              [5.74, 4.54],
              [9.17, 2.51],
              [7.79, 3.42],
              [7.93, 0.79]
             ]
raw_data_y = [0,0,0,0,0,1,1,1,1,1]

x_train = np.array(raw_data_x)
y_train = np.array(raw_data_y)

x = np.array([8.09, 3.36])

In [2]:
%run E:\Anaconda3\Lib\site-packages\playML/kNN.py

In [3]:
kNN_classify(6, x_train, y_train,x)

1

## 使用scikit-learn中的kNN

In [4]:
from sklearn.neighbors import KNeighborsClassifier

In [5]:
kNN_classifier = KNeighborsClassifier(n_neighbors=6)

In [6]:
kNN_classifier.fit(x_train,y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=1, n_neighbors=6, p=2,
           weights='uniform')

In [7]:
kNN_classifier.predict(x)

ValueError: Expected 2D array, got 1D array instead:
array=[8.09 3.36].
Reshape your data either using array.reshape(-1, 1) if your data has a single feature or array.reshape(1, -1) if it contains a single sample.

In [8]:
X_predict = x.reshape(1,-1)

In [9]:
X_predict

array([[8.09, 3.36]])

In [11]:
kNN_classifier.predict(X_predict)

array([1])

In [12]:
y_predict=kNN_classifier.predict(X_predict)
y_predict

array([1])

## 重新整理我们的kNN的代码

In [16]:
%run E:\Anaconda3\Lib\site-packages\playML/kNN.py

In [17]:
knn_clf = KNNClassifier(k=6)

In [18]:
knn_clf.fit(x_train,y_train)

In [19]:
y_predict = knn_clf.predict(X_predict)

In [20]:
y_predict

[1]

In [21]:
y_predict[0]

1